eureka:
  instance:
    hostname: 192.168.1.183
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
spring:
  security:
    user:
      name: lyn
      password: 123456
    
