eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:discoverypassword@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: a-service
          uri: lb://a-service
          order: 100
          predicates:
            - Path=/A/**
        - id: b-service
          uri: lb://b-service
          order: 100
          predicates:
            - Path=/B/**
