server:
  port: 8899


      
eureka:
  client:
    service-url:
     defaultZone: http://lyn:123456@127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
    datasource:
      username: root
      password: 1995
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.102.96.89:3306/ssotest?serverTimezone=GMT%2B8&characterEncoding=utf8
      dbcp2:
        validation-query: select * from 1
      schema: classpath:/schema.sql
      data: classpath:/data.sql
